# Generated by Django 4.0.6 on 2022-07-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_category_message_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('reg_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Obunachi',
                'verbose_name_plural': "Obuna bo'lganlar",
            },
        ),
        migrations.AddField(
            model_name='news',
            name='text_en',
            field=models.TextField(help_text='Yangilik matnini yozing', null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='text_ru',
            field=models.TextField(help_text='Yangilik matnini yozing', null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='text_uz',
            field=models.TextField(help_text='Yangilik matnini yozing', null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(help_text='Yangilik nomimi yozing', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(help_text='Yangilik nomimi yozing', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_uz',
            field=models.CharField(help_text='Yangilik nomimi yozing', max_length=50, null=True),
        ),
    ]
